Для рк
java-park-mail-ru/puzzle-09-2016 pull request #1
Opened 2016-09-25 21:03 UTC by rashemihmih

2016-09-27 14:24 UTC, isopov requested changes
Сделайте, пожалуйста, простенький .gitignore - в нем точно должна быть /target, и было бы круто, если бы там были хотя бы части .idea (моя б воля, я бы вообще все идеевские файлы, кроме профиля инспекий заигнорил, но вы можете делать, как вам удобнее)

2016-09-27 14:24 UTC, isopov commented on pom.xml
> +    <artifactId>test</artifactId>
Впишите, пожалуйста, сюда название вашего проекта, например "puzzle"

2016-09-27 14:24 UTC, isopov commented on src/main/java/ru/mail/park/services/AccountService.java
> +    private Map<String, UserProfile> userNameToUser = new HashMap<>();
Здесь нужен ConcurrentHashMap вместо обычного HashMap

2016-09-27 14:24 UTC, isopov commented on src/main/java/ru/mail/park/services/AccountService.java
> +    private Map<String, UserProfile> sessionIdToUser = new HashMap<>();
Мы вам это сами показали, но я бы так всё-таки не делал. Если не пользоваться чем-то встроенным в Spring (spring-security действительно довольно сложный а подружить его с REST-клиентом еще сложнее, поэтому мы вам его не даём, и в реальных проектах его тоже часто не используют поэтому), то я бы просто в аттрибут сессии добавлял имя пользователя и уже по имени доставал UserProfile. Типа

HttpSession.setAttribute("username", username);

2016-09-27 14:25 UTC, isopov commented on pom.xml
> +        <version>1.4.0.RELEASE</version>
Уже новая версия вышла - не хотите обновиться?

2016-09-27 18:19 UTC, rashemihmih commented
Спасибо за ответ! Вроде все поправил.

2016-10-04 06:54 UTC, isopov approved these changes

2016-10-04 06:54 UTC, isopov commented on pom.xml
> +            <groupId>junit</groupId>
junit приходит вместе со spring-boot-starter-test - отдельно его подключать не надо

2016-10-04 15:00 UTC, merged