Игровая механика
java-park-mail-ru/puzzle-09-2016 pull request #3
Opened 2016-11-30 17:46 UTC by rashemihmih

2016-11-30 18:27 UTC, KSolovyev requested changes
Не вижу тестов на механику

2016-11-30 18:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +    @Transactional
Не вижу анотации `@EnableTransactionManagement`.
Кромет того `@Transactional` работает через cgi-proxy. Это значит что в рантайме генерируется класс-обертка над вашим классом. Соответственно транзакционно будут работать только public методы, вызванные не изнутри экземпляра данного класса

2016-11-30 18:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        if (list.size() % 2 == 1) {
не, так не пойдет. Придумайте как сделать, чтобы нечетный вообще в список не добавлялся

2016-11-30 18:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameExecutorService.java
> +        while (true) {
А зачем вам вообще цикл в пошаговой игре?

2016-11-30 18:37 UTC, rashemihmih commented
Спасибо за ответ. Тестов нет. Насчет цикла, я просто делал по примеру с лекции

2016-12-01 06:45 UTC, rashemihmih commented
Вроде все поправил. Еще, кстати, насчет цикла, у нас не пошаговая игра. Игроки одновременно решают пазл - кто быстрее.

2016-12-02 10:46 UTC, rashemihmih commented
Переделал механику

2016-12-06 20:49 UTC, KSolovyev requested changes

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/mechanics/Square.java
> +        } catch (IndexOutOfBoundsException ignore) {
нет. Давайте уберем это и напишем нормально код

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        if (!queue.contains(userProfile) && gameSessions.stream().noneMatch(session -> session.contains(userProfile))) {
нужно избавится от итераций по сессиям. Это будет работать, пока их немного. Дальше производительность начнет быстро деградировать

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        if (!queue.contains(userProfile) && gameSessions.stream().noneMatch(session -> session.contains(userProfile))) {
и от итераций по игрокам тоже

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        gameSessions.stream().filter(session -> session.contains(userProfile)).findAny().
здесь тоже нужно убрать итерацию

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        if (session.isWinner(player) || !isConnected(session.getOpponent(player).getUser())) {
давайте будем присуждать победу по дисконекту в обработчике веб сокета. А здесь трогать не будем

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/messaging/ServerSnapService.java
> +    private void sendSnapsForSession(GameSession session, boolean gameOver, String winner) throws IOException {
для winner'а нужно проставить аннотацию jetbrains.annotations.Nullable

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/messaging/ServerSnapService.java
> +        final Player second = session.getSecond();
давайте вынесем действия с пользователем в отдельную функцию и вызовем ее два раза

2016-12-06 20:49 UTC, KSolovyev commented on src/test/java/GameMechTest.java
> +        assertEquals(square, session.getFirst().getSquare());
Во-первых хочется честного интеграционного теста через игровую механику.
Во-вторых данный тест нечестно делает проверку. По сути он сравнивает, что на обоих squares вызвался метода activate с одними и теми же параметрами

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        session.processAction(player, action);
давайте тут засинхронизируемся на session, чтобы у нас одновременные действия ничего не сломали

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/websocket/GameSocketHandler.java
> +        if (sessionLogin == null) {
копи паста. Вынесите ее в отдельную функцию

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/websocket/GameSocketHandler.java
> +        remotePointService.removeUser(userProfile);
здесь нужно посмотреть, что у человека творится с играми

2016-12-06 20:49 UTC, KSolovyev commented on src/main/java/ru/mail/park/websocket/GameSocketHandler.java
> +        logger.warn("Websocket transport problem", throwable);
давайте уберем в дебаг. А то может быть слишком много логов

2016-12-06 20:52 UTC, KSolovyev commented
Из общего, хочется больше тестов. Функционального теста, в котором вся игра происходит, так и не увидел. Напишите парочку - тройку с разными сценариями.

2016-12-07 19:15 UTC, KSolovyev requested changes

2016-12-07 19:15 UTC, KSolovyev commented on src/main/java/ru/mail/park/game/GameMechService.java
> +        final Player opponent = session.getOpponent(session.getPlayer(userProfile));
вот тут тоже нужно синхронизироваться на сессии

2016-12-15 21:19 UTC, KSolovyev commented
Если это рабочая версия, то давайте мержить

2016-12-16 10:43 UTC, rashemihmih commented
Давайте

2016-12-16 23:11 UTC, merged